### ISSUE TITLE
Incompatible with lpeg >= 1.1 (version parsing)

### ISSUE THREAD

**Issue by trougnouf** [harningt/luajson#47]
luajson no longer works with lpeg 1.1: `LUA ERROR : /usr/share/lua/5.4/json/decode/util.lua:97: attempt to call a string value (field 'version')`.

```lua
> lpeg = require("lpeg")
> lpeg.version
LPeg 1.1.0
> tonumber(lpeg.version():match("^(%d+%.%d+)"))
stdin:1: attempt to call a string value (field 'version')
stack traceback:
	stdin:1: in main chunk
	[C]: in ?
> lpeg.version()
stdin:1: attempt to call a string value (field 'version')
stack traceback:
	stdin:1: in main chunk
	[C]: in ?
```

I don't know what was the previous behavior of lpeg.version and lpeg.version().

I tried to fix this with

```lua
local v = lpeg.version or ""
local DecimalLpegVersion = tonumber(string.match(v, "%d+%.?%d*")) or 0.7
```

but I get 

```lua
> luajson = require('json')
/usr/share/lua/5.4/json/decode/util.lua:98: attempt to index a nil value (local '_ENV')
```

**Comment by Neph-Oo** [comment]
Hi all,

You're right @trougnouf.  This issue is still present and should not be closed. 

_ENV is set to nil at [the begining of util.lua](https://github.com/harningt/luajson/blob/fe15ca1753cbd65876dfe9987e44dec9304d6b46/lua/json/decode/util.lua#L22) and that's why when you call string.match you have this error:
```
> luajson = require('json')
/usr/share/lua/5.4/json/decode/util.lua:98: attempt to index a nil value (local '_ENV')
```

See #48 for details.

**Comment by Omikhleia** [comment]
Hello folks, do you plan a luarocks version update at some point, for those installing this nice module through it?
